%This file was automatically generated by--Generate_RobotPlot--
clear L
clear Daux
clear Dr
clear sigma

sigma(1,1)=0;
sigma(2,1)=0;
sigma(3,1)=0;
sigma(4,1)=0;
sigma(5,1)=0;
sigma(6,1)=0;

Daux(1,1)=-1.570796e+00;%alfa
Daux(1,2)=5.000000e-01;%a
Daux(1,4)=5.000000e-01;%D
Daux(1,3)=0;%theta

Daux(2,1)=0;%alfa
Daux(2,2)=5.000000e-01;%a
Daux(2,4)=5.000000e-01;%D
Daux(2,3)=-1.570796e+00;%theta

Daux(3,1)=-1.570796e+00;%alfa
Daux(3,2)=0;%a
Daux(3,4)=0;%D
Daux(3,3)=1.570796e+00;%theta

Daux(4,1)=-1.570796e+00;%alfa
Daux(4,2)=0;%a
Daux(4,4)=5.000000e-01;%D
Daux(4,3)=0;%theta

Daux(5,1)=1.570796e+00;%alfa
Daux(5,2)=0;%a
Daux(5,4)=0;%D
Daux(5,3)=0;%theta

Daux(6,1)=0;%alfa
Daux(6,2)=0;%a
Daux(6,4)=5.000000e-01;%D
Daux(6,3)=0;%theta

fprintf(1,'     alfa      a        theta      d      sigma\n');
Dr=[Daux,sigma]
L{1}=(link(Dr(1,:),'standard'));
L{2}=(link(Dr(2,:),'standard'));
L{3}=(link(Dr(3,:),'standard'));
L{4}=(link(Dr(4,:),'standard'));
L{5}=(link(Dr(5,:),'standard'));
L{6}=(link(Dr(6,:),'standard'));
base=[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1];
clear Robot_robotF
Robot_robotF=robot(L,'Robot-robotP','Fabricante_robot');
Robot_robotF.base=base;
Robot_robotF.plotopt={'nobase'};
% Robot_robotF.plotopt={'nobase' 'workspace' [-1.5 1.5 -1.5 1.5 -0.1 1.5] 'mag' 13};
clear L
clear Dr
clear Daux
clear sigma
